### ISSUE TITLE
I'm sure it's just my error

### ISSUE THREAD

**Issue by roadkingvrod** [grugnoymeme/flipperzero-CLI-wifi-cracker#4]
I've tried running this in Windows, Ubuntu, and Kali, but it crashes nearly ever time.  Would you mind sharing the specific environment and requirements that you use?

**Comment by grugnoymeme** [comment]
hey its everything explained in the readme file..no one who tried it never said me about "crash" also bc its very light weight script.. please be more precise, do a copy paste of the error(s) you get or i cannot help you sorry! 😄

**Comment by roadkingvrod** [comment]
After dinking around, i made it work on Kali.  thank you for responding. sorry for the open ticket.
