### ISSUE TITLE
Invalid input file. Please make sure the file exists and has a valid format. (Mas os). ???

### ISSUE THREAD

**Issue by pullghjunkkk** [grugnoymeme/flipperzero-CLI-wifi-cracker#5]
Insert input .pcap file's NAME or PATH: /Users/paulchikkkk/Desktop/sniffpmkid_2.pcap 
Invalid input file. Please make sure the file exists and has a valid format.
Insert input .pcap file's NAME or PATH: sniffpmkid_2.pcap 
Invalid input file. Please make sure the file exists and has a valid format.
Insert input .pcap file's NAME or PATH:

**Comment by grugnoymeme** [comment]
you dont have to use a file "sniffpmkid".. read the instructions.... you'll find a script to deauth and sniff or the instructions to make it on your own... anyway... the right way to sniff eapol to get analized by my tool is with "raw sniff", but not only that.. please read the readme file. ;)
